name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ec2-3-110-51-98.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_DEPLOY_KEY }}
        script: |
          bash /home/ubuntu/bms-api/bms-apis/deploy.sh
